const products = [
  {
    id: "p1",
    name: "Stylish T-Shirt",
    price: 2499.99,
    category: "Fashion",
    image: "Shirt.jpg",
    description: "Comfortable and trendy T-Shirt made from organic cotton.",
  },
  {
    id: "p2",
    name: "Wireless Headphones",
    price: 3499.99,
    category: "Electronics",
    image: "headphone.jpg",
    description: "High quality sound and noise cancellation for your music.",
  },
  {
    id: "p3",
    name: "Ceramic Vase",
    price: 1499.0,
    category: "Home & Living",
    image: "istockphoto-1300939276-612x612.jpg",
    description: "Elegant vase to add charm to your living room.",
  },
  {
    id: "p4",
    name: "Natural Lip Balm",
    price: 999.99,
    category: "Beauty",
    image: "make-homemade-natural-organic-ingredients-260nw-1881057844.webp",
    description: "Hydrating and organic lip balm with natural ingredients.",
  },
  {
    id: "p5",
    name: "Denim Jeans",
    price: 1299.99,
    category: "Fashion",
    image: "jeans.jpg",
    description: "Classic fit denim jeans with durable fabric.",
  },
  {
    id: "p6",
    name: "Smartphone",
    price: 149999.99,
    category: "Electronics",
    image: "photo_2025-06-29_20-25-57.jpg",
    description: "Latest model with all the features you need.",
  },
  {
    id: "p7",
    name: "Scented Candle",
    price: 199.99,
    category: "Home & Living",
    image: "candle.jpg",
    description: "Relaxing aroma to brighten up your home.",
  },
  {
    id: "p8",
    name: "Moisturizer Cream",
    price: 3999.99,
    category: "Beauty",
    image: "BEST-FACIAL-MOISTURIZERS-SUB-2048px-1830.webp",
    description: "Keeps your skin hydrated and soft all day.",
  },
  {
    id: "p9",
    name: "Black Hoodie",
    price: 2999.99,
    category: "Fashion",
    image: "black-hoodie.png",
    description: "Comfortable and trendy Hoodie made from organic cotton.",
  },
  {
    id: "p10",
    name: "Winter Coat",
    price: 2999.99,
    category: "Fashion",
    image: "Winter-Coat.png",
    description: "Comfortable and trendy Hoodie made from organic cotton.",
  },
  {
    id: "p11",
    name: "High Heel",
    price: 2999.99,
    category: "Fashion",
    image: "women shoes.jpg",
    description: "Comfortable and trendy Hoodie made from organic cotton.",
  },
  {
    id: "p12",
    name: "Modern Bed Interior",
    price: 9999.99,
    category: "Home & Living",
    image: "Modern Bed Interior.jpg",
    description: "Comfortable and trendy Bed made from organic Wood.",
  },
  {
    id: "p13",
    name: "ottoman empire furniture with classic ornaments",
    price: 3999.99,
    category: "Home & Living",
    image: "ottoman empire furniture with classic ornaments.jpg",
    description: "Comfortable and trendy Bed made from organic Wood.",
  },
  {
    id: "p14",
    name: "French Furniture With classical Ornaments",
    price: 3999.99,
    category: "Home & Living",
    image: "French Furniture With classical Ornaments.jpg",
    description: "Comfortable and trendy Bed made from organic Wood.",
  },
  {
    id: "p15",
    name: "High Performance GPU with Cyberpunk Coolers",
    price: 19999.99,
    category: "Electronics",
    image: "High Performance GPU with Cyberpunk Coolers.jpg",
    description: "High quality strong GPU for your PC.",
  },
  {
    id: "p17",
    name: "Black Power Bank 18W",
    price: 3499.99,
    category: "Electronics",
    image: "Black Power Bank 18W.jpg",
    description: "High quality sustainable power bank for your Phone.",
  },
  {
    id: "p18",
    name: "Apple MacBook Air (M4)",
    price: 199999.99,
    category: "Electronics",
    image: "laptop.jpg",
    description: "High quality performence MacBook",
  },
  {
    id: "p19",
    name: "Vibrant Colors of Eyeshadow",
    price: 3999.99,
    category: "Beauty",
    image: "Vibrant Colors of Eyeshadow.jpg",
    description: "Keeps your eyes colorful hydrated and beautiful all day.",
  },
  {
    id: "p20",
    name: "Pink Nail polish with Golden Glitter",
    price: 3999.99,
    category: "Beauty",
    image: "Pink Nail polish with Golden Glitter.jpg",
    description: "Keeps your nails shiney and colorful all day.",
  },
  {
    id: "p21",
    name: "Crimson LipStick",
    price: 3999.99,
    category: "Beauty",
    image: "Crimson LipStick.jpg",
    description: "Keeps your lip red and soft all day.",
  },
];
